version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: abd_postgres
    environment:
      POSTGRES_USER: abd_user
      POSTGRES_PASSWORD: abd_password
      POSTGRES_DB: abd_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: